### ISSUE TITLE
Illustrator Driver Issue

### ISSUE THREAD

**Issue by alnavasa** [thenickdude/wacom-driver-fix#66] opened 2021-03-11 10:07 UTC
Illustrator gives me an error no matter what I do.

`Install-Wacom-Tablet-5.3.7-6-patched`

<img width="697" alt="Captura de pantalla 2021-03-11 a las 11 06 23" src="https://user-images.githubusercontent.com/458370/110770684-e7f18f00-8259-11eb-83a5-75c1c12f7b85.png">

**Comment by thenickdude** [comment] 2021-03-11 10:19
Duplicate of #63

**Closed by thenickdude** 2021-03-11 10:19 UTC
